### ISSUE TITLE
Off topic question

### ISSUE THREAD

**Issue by Botspot** [SkywalkerSW5/ddw#1]
This is really off-topic (I know), but it looks like you forked [my Pi-Power-Tools](https://github.com/Botspot/Pi-Power-Tools) and tried to improve it.
And then you deleted the whole repository?!

I'd be glad to help you adapt it, and will gladly answer your questions about it.
If you have any suggestions on how to improve Pi-Power-Tools, I'd love to hear them!

**Comment by SkywalkerSW5** [comment]
Hello!

I guess my notifications weren't on but I did fork it because there was an error (vdesktop) which I think had something due to Raspbian being installed to my hard drive, and tried to fix it. However I couldn't fix it and I had to use the hard drive. Besides that, the app was awesome!

Also the "this is my url" repo was a project I forgot what it was about, and because I had to upload a picture for school on my chromebook, and they blocked everything I could upload it to, I uploaded that dog picture there.

**Comment by Botspot** [comment]
OK. I've made quite a few bug fixes to vdesktop since then. If you're willing to update vdesktop and try again, that would be great. And if it still doesn't work, I would really like to see the error messages so I can improve vdesktop.

:)
